
<!DOCTYPE Employees [
 <!ELEMENT Employees (Employee+)>
 <!ELEMENT Employee (name,salary,department)>
 <!ELEMENT name (#PCDATA)>
 <!ELEMENT salary (#PCDATA)>
 <!ELEMENT department (#PCDATA)>
]> 
<Employees>
    <Employee>
        <name>Asim</name>
        <salary>30000</salary>
        <department>Data Entery Operator</department>
    </Employee>
    <Employee>
        <name>Saim</name>
        <salary>20000</salary>
        <department>Data Entery Operator</department>
    </Employee>
    <Employee>
        <name>Danish</name>
        <salary>40000</salary>
        <department>Data Entery Operator</department>
    </Employee>
    <Employee>
        <name>Hasnain</name>
        <salary>50000</salary>
        <department>Data Entery Operator</department>
    </Employee>
    <Employee>
        <name>Shabir</name>
        <salary>25000</salary>
        <department>Data Entery Operator</department>
    </Employee>
    <Employee>
        <name>Murtaza</name>
        <salary>31000</salary>
        <department>Data Entery Operator</department>
    </Employee>
    <Employee>
        <name>Ali</name>
        <salary>15000</salary>
        <department>Data Entery Operator</department>
    </Employee>
</Employees>